# Generated by Django 4.2.6 on 2023-11-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobiles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiles',
            name='image',
        ),
        migrations.AddField(
            model_name='mobiles',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
